baseurl = "https://blog.silvela.org/"
canonifyurls = true
disablePathToLower = true
languageCode =  "en-us"
title = "Lost Among Notes"
author = "Jaime Silvela"
theme = "lost"
# deactivate disqus # disqusShortname = "lost-among-notes"
publishdir = "public"

[params]
  copyright= "Jaime Silvela"
  twitter= "https://twitter.com/jsilvela"
  email= "jaime.silvela@gmail.com"

[markup.goldmark.renderer]
	unsafe= true